# Generated by Django 3.0.7 on 2020-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellness',
            name='image',
            field=models.ImageField(default='static/images/alexander-w-oEpnMn1y-7A-unsplash.jpg', upload_to=None),
        ),
    ]
