# Generated by Django 3.0.7 on 2020-07-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_wellness_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellness',
            name='image',
            field=models.ImageField(default='/Users/makeschoolloaner/dev/SPD1.5/decentralRize/static/images/alexander-w-oEpnMn1y-7A-unsplash.jpg', upload_to=None),
        ),
    ]
