# Generated by Django 3.0.7 on 2020-07-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0003_auto_20200709_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellness',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
