# Generated by Django 3.0.7 on 2020-07-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0004_wellness_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellness',
            name='source',
            field=models.CharField(default='source', max_length=200),
            preserve_default=False,
        ),
    ]
