# Generated by Django 3.0.7 on 2020-07-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0005_wellness_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellness',
            name='image',
            field=models.ImageField(default='/Users/makeschoolloaner/dev/SPD1.5/decentralRize/static/images/alexander-w-oEpnMn1y-7A-unsplash.jpg', upload_to='wellness'),
        ),
    ]
