# Generated by Django 3.0.7 on 2020-07-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0006_auto_20200714_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellness',
            name='image',
            field=models.FileField(blank=True, upload_to='wellness_img'),
        ),
    ]
