# Generated by Django 3.0.7 on 2020-07-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activism', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activism',
            old_name='action',
            new_name='name',
        ),
    ]
