# Generated by Django 3.0.7 on 2020-07-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activism', '0002_auto_20200709_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activism',
            old_name='name',
            new_name='action',
        ),
    ]
