# Generated by Django 3.0.7 on 2020-07-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='genre',
            field=models.CharField(default='genre', max_length=200),
            preserve_default=False,
        ),
    ]
