# Generated by Django 3.0.7 on 2020-07-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
    ]
