# Generated by Django 3.0.7 on 2020-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.URLField(),
        ),
    ]
