# Generated by Django 3.0.7 on 2020-07-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_img'),
        ('business', '0004_auto_20200715_0300'),
    ]

    operations = [
    ]
